---
#
# Playbook: Local System
#

- hosts: localhost
  connection: local
  user: changeme
  become: yes
  
# Pre-Tasks

  pre_tasks:

  - name: Pretask | Running pre tasks routine
    shell: echo 'I":" Beginning to configure the system...'

  - name: Pretask | Update apt cache
    apt: update_cache=yes

# Main-Tasks

  roles:
    - common
    - package-mgmt
    - shell-settings
    - shell-tools
    - desktop-kit
    - desktop-google-chrome
    - desktop-virtualbox
    - desktop-skype
    - desktop-teamviewer
    - local-storage
    - desktop-insync
    - desktop-fingerprint
    - desktop-vagrant
    - desktop-flux
#    - rsyslog-service
#    - openssh-service
#    - ntp-service
#    - system-update
