---
# tasks file for desktop-kit

- name: Instalación de programas para trabajo en la consola o shell
  apt: pkg={{ item }} state=installed
  with_items:
    - aptitude
    - terminator
    - yakuake
    - htop
    - vim
    - expect
    - tree
    - gzip
    - bzip2
    - zip
    - unzip
    - unrar
    - lzop
    - elinks
    - ntp
    - bind9utils
    - samba
    - winbind 
    - smbclient 
    - cifs-utils 
    - sshfs 
    - libpam-mount 
    - dnsutils 
    - whois 
    - traceroute 
    - wireshark 
    - tshark 
    - ipcalc 
    - nmap
    - wakeonlan
  tags:
    - desktop_kit_shell

- name: Instalación de paquetes para documentación técnica con Docbook
  apt: pkg={{ item }} state=installed
  with_items:
    - docbook-utils
    - docbook-xsl
    - docbook2odf
    - xsltproc
    - xmlto
    - libxml2-utils
    - fop
    - libservlet2.5-java
    - publican
  tags:
    - desktop_kit_techdoc

- name: Instalación de herramientas de seguridad para el shell y X11
  apt: pkg={{ item }} state=installed
  with_items:
    - openssl
    - libnss3-tools
    - openssh-client
    - gnupg
    - gnupg-agent
    - keychain
    - pinentry-curses
    - pinentry-qt4
    - kgpg
    - ssh-askpass
    - pwgen
    - keepassx
  tags:
    - desktop_kit_security

- name: Instalación de Herramientas para Desarrollo
  apt: pkg={{ item }} state=installed
  with_items:
    - build-essential
    - diffutils
    - cvs 
    - subversion
    - git
#    - kdesvn
    - kdiff3
    - kompare
    - mysql-workbench
  tags:
    - desktop_kit_development

- name: Instalación de Herramientas para oficina y edición de imágenes
  apt: pkg={{ item }} state=installed
  with_items:
    - xpdf
    - kcalc
    - xchm
    - dia
    - gimp
    - kolourpaint4
    - ttf-liberation
    - ttf-mscorefonts-installer
    - aspell-es
  tags:
    - desktop_kit_imageedit

#- name: Instalación de paquetes para extras para KDE
#  apt: pkg={{ item }} state=installed
#  with_items:
#    - kscreensaver
#    - kscreensaver-xsavers
#    - xscreensaver
#    - xscreensaver-gl
#    - xscreensaver-data
#    - xscreensaver-data-extra
#    - xscreensaver-gl-extra
#  tags:
#    - desktop_kit_kdeextras

- name: Instalación de paquetes para Web, IM, Correo y otros
  apt: pkg={{ item }} state=installed
  with_items:
    - firefox
    - flashplugin-installer
#    - openjdk-6-jre
    - thunderbird
    - enigmail
    - pidgin
    - pidgin-encryption
    - konversation
    - xvnc4viewer
    - rdesktop
    - krdc
    - remmina
  tags:
    - desktop_kit_web_im_mail_remote

- name: Instalación de paquetes para Audio y Video
  apt: pkg={{ item }} state=installed
  with_items:
    - lame
    - mplayer
    - mencoder
    - vlc
    - amarok
    - clementine
    - easytag
    - k3b
    - k3b-i18n
  tags:
    - desktop_kit_audiovideo

- name: Instalación de Herramientas de Productividad
  apt: pkg={{ item }} state=installed
  with_items:
    - freeplane
    - cherrytree
  tags:
    - desktop_kit_productivity
  #$ wget http://dl.ganttproject.biz/ganttproject-2.6.6/ganttproject_2.6.6-r1715-1_all.deb
  #$ sudo dpkg -i ganttproject_2.6.6-r1715-1_all.deb

- name: Instalación de sistema de virtualización KVM con virt-manager
  apt: pkg={{ item }} state=installed
  with_items:
    - qemu-kvm
    - libvirt-bin
    - virt-manager
    - virt-viewer
    - ssh-askpass
  tags:
    - desktop_kit_libvirt_desk

- name: Instalación de paquetes adicionales
  apt: pkg={{ item }} state=installed
  with_items:
    - openssh-server
    - openvpn
  tags:
    - desktop_kit_sshvpn

