---
# tasks file for shell-settings

- name: Update apt cache lists
  apt: update_cache=yes cache_valid_time=3600
  when: apt_update is not defined
  tags:
    - package_mgmt

- name: Install bash packages
  apt: pkg={{item}} state=installed
  with_items:
    - bash
    - bash-completion
  tags:
    - shell_settings

- name: Set bash alternative
  command: update-alternatives --install /bin/sh sh {{default_shell}} 1
  changed_when: False
  tags:
    - shell_settings

- name: Set bash ~/.bashrc
  copy: src=bash/root/1404dotbashrc dest=/root/.bashrc owner=root group=root mode=0640
  tags:
    - shell_settings

- name: Set bash ~/.bash_local
  copy: src=bash/root/1404dotbash_local dest=/root/.bash_local owner=root group=root mode=0640
  tags:
    - shell_settings

- name: Set bash ~/.bash_aliases
  copy: src=bash/root/1404dotbash_aliases dest=/root/.bash_aliases owner=root group=root mode=0640
  tags:
    - shell_settings
