---
# tasks file for desktop-atom

- name: Download atom dpkg package
  get_url: url={{ atom_url_deb }} dest={{ atom_tmp_deb }}
  tags:
    - desktop_atom

- name: Install atom package
  apt: deb={{ atom_tmp_deb }}
  tags:
    - desktop_atom
